### ISSUE TITLE
Feature Request: Sunrise SDK

### ISSUE THREAD

**Issue by dankelleher** [sunrise-stake/app#11]
Extract an sdk from the app, and publish it, so that it can be used by other projects. The sdk is essentially the contents of the packages/app/src/client/ folder. It should be then injected into the app and test packages as a dependency to avoid code duplication. CI should be adapted to build it and run tests but no need for CI to publish yet.

bonus points if the monorepo is adapted to use lerna/nx as part of this.

**Comment by Mjavala** [comment]
@dankelleher I'll do this one :)
