### ISSUE TITLE
Metaplex token metadata for gSOL

### ISSUE THREAD

**Issue by dankelleher** [sunrise-stake/app#12]
Ensure gSOL is shown correctly in wallets etc by setting up metadata for it

https://docs.metaplex.com/programs/token-metadata/

**Comment by s6thgehr** [comment]
Hello, 
I would like to work on that issue.

**Comment by jim4067** [comment]
@s6thgehr. Yeah. you can have a go at this. 

here are some resources to get you started https://github.com/solana-developers/program-examples/tree/main/tokens/mint-2/anchor
