### ISSUE TITLE
Usage&Trees: UI & Design Improvements (Grizzlython)

### ISSUE THREAD

**Issue by ronnyhaase** [sunrise-stake/app#143]
### Design, major
- [X]  Interactive Guide - we need to start thinking about messaging, so that people know what the hell is going on - what is the tree? What does it represent? What is the forest? How do I grow it etc. Dhevyn Emmanuel can you start thinking about how we portray that?

### Fronted, major
- [x] Reduce amount of initial requests (@dankelleher)
- [x] Fix unnecessary requests
- [x] Final push on Forest @dankelleher 
  - [x]  Forest trees to float around like the zen mode?
  - [x]  Text under the trees needs to be styled and moved
- [x] Explanation popups for each page @ronnyhaase / @dankelleher 
- [x] Update tree and forest on changes @dankelleher 
- [x] Locking all gSOL desaturates tree (still the case?) @dankelleher
- [x] Un/-Staking sometimes not updates tree (rate limit?) @dankelleher
- [ ] Optional: Visit other's forest @dankelleher 

### Frontend, minor
- [x] Stake button should show immediately if you have no stake @ronnyhaase 
- [X] Update Warning modal
- [x] Update Tweet modal @s6thgehr 
- Lock page
  - [x] Need to show current gsol balance
  - [X] tree should not bounce
  - [X] before a user has an nft, there is just a big gap in the UI
  - [x] text is unstyled and clashes with the bg (same as on the grow page)
  - [ ] Warning when unlocking in same epoch
  - [ ] Detect possibility to upgrade
- [ ] Add a pulse to the hub tree, to hint to click
- [x] Add auto-fadein Hub after 5 seconds @ronnyhaase 
- [x] Clicking tree on hub again, hides navigation
- [x] Make buttons outline
- [x] Responsive wallet button positioning
- [x] Solflare mobile app still has issues on mobile
- [x] Either the user's tree or the sunrise logo should appear at the top of each page except the hub and the forest 
- [x] All screens need a back or close button
- [x] Styling for the arrow and stake buttons on the hub
- [x] Grow and Forest screens are off-centre  on wider resolutions, for example by default on mac.
- [ ] Improve amount input on small devices
- [ ] Redeem button seems to has wrong color (should be gold when available)
- [x] Add social links at bottom left
- [ ] Help icon becomes tiny on lower resolutions
- Grow page
  - [x] More breathing space
  - [x] Remove dots
- [x] Remove background image except intro
- [x] Unstake options dropdown is not styled correctly
- [x] Improve staking screen on mobile

**Comment by dankelleher** [comment]
Comments from Juliane:

Grow page:

The end could have some breathing area. And I would take off the dots ... in the text, and also the word app. 
I would put also the arrow to go back a bit lower

**Comment by dankelleher** [comment]
Locking SOL makes tree greyed out

**Comment by dankelleher** [comment]
transfer sol popup hard to edit input
transfer popup does not close on completion
transfer popup has incorrect max amount

**Comment by dankelleher** [comment]
lock nft text needs styling
lock nft unlock button should show alert if trying to unlock in the same epoch
ideally detect if upgrade is possible on lock nft screen

**Comment by dankelleher** [comment]
remove background for all except wallet connection page.

**Comment by dankelleher** [comment]
✅ unstake options dropdown colour issue

**Comment by dankelleher** [comment]
Staking sometimes does not update the tree (probably a rate-limit issue)

**Comment by dankelleher** [comment]
![image](https://user-images.githubusercontent.com/5008805/224681237-15c884e4-1656-4b66-999e-e005a6d1efa0.png)
Fix mobile spacing on stake screen

**Comment by ronnyhaase** [comment]
Leftover tasks moved to #173
