### ISSUE TITLE
Feature Request: Integrate with Marinade's Open Doors program

### ISSUE THREAD

**Issue by jonnyplatt** [sunrise-stake/app#25]
Marinade are launching an 'open doors' program, which seeks to reward protocols who bring new stake to Marinade by granting them MNDE tokens as a form of referral / affiliate payment.

It would be a great idea to integrate with this, as the additional MNDE received for staking gSOL with Marinade could be added to the treasury and used for a range of useful activities, for instance:

* Offering an additional incentive for stakers so they still receive at least some yield
* Creating a marketing fund that could be used to promote Sunrise more widely
* Selling the MNDE for SOL which Sunrise could then stake into the pool, increasing the yield for more NCT purchases
* ...?

**Comment by ronnyhaase** [comment]
- Invest a share in a Chef NFT to participate in Marinade Governance in Sunrise's interests

**Comment by dankelleher** [comment]
Just to emphasise here, any investments made by the protocol have to be risk-free. So if it is a reward program for staking mSol long-term then 👍 . If we have to lock msol into a pool to earn MNDE, and that pool is subject to IL risk, then we would have to carefully think about it.

**Comment by jonnyplatt** [comment]
Open doors on its own is effectively a referral program: bring more TVL to marinade and earn their MNDE token in kind. It would involve no extra risk. I believe all that is required is to pass the referral ID and you will be automatically included.

There are other higher risk ways to earn MNDE that may not be relevant, however this one is pretty straight forward

**Comment by ronnyhaase** [comment]
Hi, just to have this issue up to date: I'm on it.
I'm in touch with Cerba from Marinade, created the forum post and provided an RPC call to check our mSOL TVL. I'm only waiting for the final confirmation.

No referral, risk or lock-in:
> Protocols that participate in the Open Doors program and contain mSOL in their TVL (pools, vaults staking, etc.) will be tracked daily by Marinade. mSOL deposited and staying in these protocols between Feb. 1, 2023 and January 31, 2024 will be eligible for MNDE rewards of up to 4 MNDE per 1 mSOL held over 12 months. 
In order to calculate the TVL brought to Marinade, a baseline will be established on February 1st.

https://marinade.notion.site/marinade/Invitation-Marinade-Open-Doors-program-8eef7e294a7d4b51a5d8aea1fe0ca8b2

**Comment by ronnyhaase** [comment]
Marinade approved the call and will integrate it into their monitoring, so we're set until pay outs happen.
For reference, this is the code:
```js
const solana = require('@solana/web3.js')

const SUNRISE_MSOL_TOKENACCOUNT_ADDRESS = '6vRu2voMXGeMzAL12epHKKQrAv3v6EVoipNdh9u9s5L3'

new solana.Connection(process.env.RPC_URL)
  .getTokenAccountBalance(new solana.PublicKey(SUNRISE_MSOL_TOKENACCOUNT_ADDRESS))
  .then(resp => console.log(resp.value))
```

Output:
```json
{
  amount: '124808900983',
  decimals: 9,
  uiAmount: 124.808900983,
  uiAmountString: '124.808900983'
}
```
